### ISSUE TITLE
Requiring consul.service on systemd breaks fabio last-known-good routes

### ISSUE THREAD

**Issue by aharkness** [lobsterdore/ansible-fabio#14]
One nice feature of fabio is that if the local consul agent fails, fabio will continue serving its last known good routing table.  It won't update that table until consul is back, but at least it can keep serving.

By requiring consul.service, this handy functionality is broken.

I propose depending on network online instead of consul.

**Comment by lobsterdore** [comment]
This sounds reasonable to me, feel free to submit a PR :)
