### ISSUE TITLE
fabio now requires go 1.7

### ISSUE THREAD

**Issue by aerickson** [lobsterdore/ansible-fabio#6]
The current code uses 1.5. Fabio still compiles, but behaves strangely.

**Comment by aerickson** [comment]
The following is working for me.

```
fabio_go_checksum: "47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b"
fabio_go_version: 1.7.4
```

**Comment by lobsterdore** [comment]
Your fix sholud work just fine, there is now an option to simply use a release which gets around  [this issue completely](https://github.com/lobsterdore/ansible-fabio/commit/8dbc14e24753b6bea6198243c6c5b1b1145a804e)

**Comment by kostyrev** [comment]
Yep, controlled by this [toggle](https://github.com/lobsterdore/ansible-fabio/blob/master/defaults/main.yml#L14)
